In [1]:
#Script perform COMBAT harmonisation
#CSV file with one column per subject one row per ROI
'original code https://github.com/Jfortin1/neuroCombat'


'original code https://github.com/Jfortin1/neuroCombat'

In [2]:
from neuroCombat import neuroCombat
import pandas as pd
import numpy as np

In [3]:
data = pd.read_csv('/Users/charlie/Desktop/my_projects/neurotransmitter/github/data/mind_node.csv')
data = data.values

covariates = pd.read_csv('/Users/charlie/Desktop/my_projects/neurotransmitter/github/data/demos_long.csv')
# Remove the first column
covariates = covariates.drop(covariates.columns[3], axis=1)
covariates = covariates.drop(covariates.columns[0], axis=1)
covariates = covariates.drop(covariates.columns[4], axis=1)
print(covariates)

#Specify categorical columns
categorical_cols = ['sex', 'group']
#Specify scanner variable
##Here I assigned a different value to each scanner in each site in each study
batch_col = 'site'

data_combat = neuroCombat(dat=data,
    covars=covariates,
    batch_col=batch_col,
    categorical_cols=categorical_cols)["data"]

file_path = '/Users/charlie/Desktop/my_projects/neurotransmitter/github/results/data_combat.csv'
np.savetxt(file_path, data_combat, delimiter=',', fmt='%s')

print(data)
print(data_combat)

     site  sex  group  age1     eTIV
0       1    1      2   265  1225971
1       2    2      2   222  1309999
2       3    1      2   301  1770252
3       4    1      2   310  1606876
4       1    2      2   271  1499895
..    ...  ...    ...   ...      ...
216     4    2      0   388  1472688
217     1    2      0   342  1458711
218     1    2      0   390  1380172
219     4    2      0   359  1273589
220     3    2      0   247  1325803

[221 rows x 5 columns]
[neuroCombat] Creating design matrix
[neuroCombat] Standardizing data across features
[neuroCombat] Fitting L/S model and finding priors
[neuroCombat] Finding parametric adjustments
[neuroCombat] Final adjustment of data
[[0.1861886  0.14731975 0.13469141 ... 0.16440402 0.14883429 0.17271033]
 [0.12130742 0.11687492 0.1369239  ... 0.13314168 0.114083   0.12968831]
 [0.19710537 0.18340937 0.18021502 ... 0.18210276 0.1824831  0.18492208]
 ...
 [0.08103051 0.07940067 0.07488576 ... 0.07289963 0.07908921 0.08052219]
 [0.11804473 0